/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * BCP PDF Extractor
 * Extracts transactions from PDF documents and manages document types.
 * OpenAPI spec version: 2.0.0
 */
import type {
  DTOGetCategoriesResponse
} from '../bcp.schemas';


export type getCategoriesCategoriesGetResponse200 = {
  data: DTOGetCategoriesResponse
  status: 200
}

export type getCategoriesCategoriesGetResponseSuccess = (getCategoriesCategoriesGetResponse200) & {
  headers: Headers;
};
;

export type getCategoriesCategoriesGetResponse = (getCategoriesCategoriesGetResponseSuccess)

export const getGetCategoriesCategoriesGetUrl = () => {




  return `http://new-service:8000/categories/`
}

/**
 * Get all categories
 *
 * Returns:
 *     List of all categories with their details
 * @summary Get Categories
 */
export const getCategoriesCategoriesGet = async ( options?: RequestInit): Promise<getCategoriesCategoriesGetResponse> => {

  const res = await fetch(getGetCategoriesCategoriesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCategoriesCategoriesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCategoriesCategoriesGetResponse
}


