services:

  new-service:
    container_name: new-service-container
    build: 
      context: ./new-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_SERVER
    depends_on:
      new-service-init:
        condition: service_completed_successfully
    volumes:
      - ./files:/shared_files
      - /mnt/c/Users/josue/Downloads:/downloads

  new-service-init:
    build: ./new-service
    command: bash scripts/prestart.sh
    env_file:
      - .env
    container_name: new-service-init-container
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db-container
    image: postgres:15
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      # - POSTGRES_SERVER
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PATH_TO_SHARED_FILES
      - AUTH_SECRET
    volumes:
      - ./files:/shared_files
      - /mnt/c/Users/josue/Downloads:/downloads

volumes:
  pgadmin_data:
