services:

  new-service:
    container_name: new-service-container
    build: 
      context: ./new-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_SERVER
      - PDF_PASSWORD
      - BACKEND_URL
      - TESSERACT_SERVICE_URL
    depends_on:
      new-service-init:
        condition: service_completed_successfully
      tesseract:
        condition: service_started
    volumes:
      - ./files:/shared_files
      - /mnt/c/Users/josue/Downloads:/downloads
      # We need to document the way each document is extracted. This is important

  tesseract:
    container_name: tesseract-container
    image: hertzg/tesseract-server:latest
    ports:
      - "8884:8884"

  new-service-init:
    build: ./new-service
    command: poetry run bash scripts/prestart.sh
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_SERVER
    container_name: new-service-init-container
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db-container
    image: postgres:15
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      # - POSTGRES_SERVER
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PATH_TO_SHARED_FILES
      - AUTH_SECRET
    volumes:
      - ./files:/shared_files
      - /mnt/c/Users/josue/Downloads:/downloads

# https://jupyter-docker-stacks.readthedocs.io/en/latest/
  jupyter:
    image: quay.io/jupyter/scipy-notebook:2026-07-28
    container_name: jupyter-container
    ports:
      - "10000:8888"
    volumes:
          - ./jupyter:/home/jovyan/work

volumes:
  pgadmin_data:
