/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * BCP PDF Extractor
 * Extracts transactions from PDF documents and manages document types.
 * OpenAPI spec version: 2.0.0
 */
/**
 * Single transaction update item - DTO for batch update request
 */
export interface DTOBatchUpdateRequest {
  transaction_id: string;
  history: string;
  category_name?: string;
}

/**
 * DTO for category entity - used for transferring data between controllers and use cases
 */
export interface DTOCategory {
  id: string;
  name: string;
  description: string;
  parent_id?: string | null;
}

export interface DTOCreateDocumentRequest {
  pdf_filepath: string;
  user_email: string;
  document_type: string;
}

/**
 * Result DTO for PDF processing - returned from use case to controller
 */
export interface DTOCreateDocumentResponse {
  success: boolean;
  document_id: string;
  unique_identifier: string;
  already_exists: boolean;
  transactions_count: number;
  message: string;
}

/**
 * Result DTO for loading transactions operation - returned from use case to controller
 */
export interface DTOCreateTransactionsResponse {
  success: boolean;
  loaded_count: number;
  skipped_count: number;
  errors: string[];
  total_records: number;
  document_id: string;
}

/**
 * Result DTO for export transactions operation - returned from use case to controller
 */
export interface DTOExportTransactionsResponse {
  success: boolean;
  csv_content: string;
  filename: string;
  transaction_count: number;
  file_path?: string | null;
  month?: string | null;
  document_id?: string | null;
  error_message?: string | null;
}

export type DTOGetAllDocumentTypesResponseDocumentTypesItem = { [key: string]: unknown };

/**
 * Response DTO for get all document types operation - returned from use case to controller
 */
export interface DTOGetAllDocumentTypesResponse {
  document_types: DTOGetAllDocumentTypesResponseDocumentTypesItem[];
  total_count: number;
}

/**
 * Transaction entity - represents a bank transaction
 */
export interface TransactionEntity {
  order?: number;
  description?: string;
  history?: string | null;
  amount?: number;
  transaction_type?: string;
  transaction_date?: string | null;
  currency?: string;
  unique_identifier?: string | null;
  category_id?: string | null;
  document_id?: string | null;
  id?: string | null;
  category_name?: string | null;
  document_type_name?: string | null;
}

/**
 * DTO for get all transactions response
 */
export interface DTOGetAllTransactionsResponse {
  transactions: TransactionEntity[];
}

/**
 * Response DTO for get all categories operation - returned from use case to controller
 */
export interface DTOGetCategoriesResponse {
  categories: DTOCategory[];
  total_count: number;
}

export type DocumentEntityDataItem = { [key: string]: unknown };

/**
 * Document entity - represents a financial document
 */
export interface DocumentEntity {
  data?: DocumentEntityDataItem[];
  unique_identifier?: string | null;
  processed?: boolean;
  start_date?: string | null;
  end_date?: string | null;
  user_id?: string | null;
  document_type_id?: string | null;
  id?: string | null;
  plain_text?: string | null;
  document_type_name?: string | null;
}

/**
 * Response DTO for get all documents operation - returned from use case to controller
 */
export interface DTOGetDocumentsResponse {
  documents: DocumentEntity[];
  total_returned: number;
  skip: number;
  limit: number;
}

/**
 * Result DTO for import transactions operation - returned from use case to controller
 */
export interface DTOImportTransactionsFromCsvResponse {
  success: boolean;
  updated_count: number;
  skipped_count: number;
  errors: string[];
  total_rows: number;
  message: string;
}

/**
 * DTO for updating a single transaction - request from controller to use case
 */
export interface DTOUpdateTransactionRequest {
  history?: string | null;
  category_name?: string | null;
}

/**
 * Result DTO for update transaction operation - returned from use case to controller
 */
export interface DTOUpdateTransactionResponse {
  transaction_id: string;
  updated: boolean;
  message: string;
}

/**
 * Wrapper DTO for batch update list request - input from controller
 */
export interface DTOUpdateTransactionsRequest {
  updates: DTOBatchUpdateRequest[];
}

export type DTOUpdateTransactionsResponseErrorsItem = { [key: string]: unknown };

/**
 * Result DTO for batch update operation - returned from use case to controller
 */
export interface DTOUpdateTransactionsResponse {
  total: number;
  updated: number;
  failed: number;
  errors: DTOUpdateTransactionsResponseErrorsItem[];
  message?: string | null;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type GetTransactionsTransactionsGetParams = {
skip?: number;
limit?: number;
};

export type ExportTransactionsTransactionsExportCsvGetParams = {
/**
 * Filter by month in format YYYY-MM (e.g., 2025-01)
 */
month?: string | null;
/**
 * Filter by document ID
 */
document_id?: string | null;
/**
 * Output directory for exported CSV files
 */
output_dir?: string;
};

export type ImportTransactionsFromCsvTransactionsImportCsvPostParams = {
/**
 * Specific CSV filename to import (optional, uses latest if not provided)
 */
csv_filename?: string | null;
/**
 * Directory where to read the CSV file from
 */
input_dir?: string;
};

export type GetDocumentsDocumentGetParams = {
/**
 * Number of records to skip
 * @minimum 0
 */
skip?: number;
/**
 * Maximum number of records to return
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
};

export type DeleteDocumentDocumentDocumentIdDelete200 = { [key: string]: unknown };

