# Flow to create new document and extract transactions from it

@host = localhost:8000
@path = /downloads
@fileName = EECC062026_05628441.PDF

### 1. Create a new document

# @name createDocument
POST http://{{host}}/document HTTP/1.1
content-type: application/json

{
  "document_format": "bcp_debit",
  "pdf_filepath": "{{path}}/{{fileName}}",
  "user_email": "admin@bcpextractor.com"
}

### 2. Create transactions from the created document

# @name createTransactions
POST http://{{host}}/transactions/{{createDocument.response.body.$.document_id}} HTTP/1.1
content-type: application/json

### 3. Export transactions to CSV

# @name exportTransactions
GET http://{{host}}/transactions/export?document_id={{createDocument.response.body.$.document_id}} HTTP/1.1
content-type: application/json
