# Flow to create new document and extract transactions from it

@host = localhost:8000

###

# @name getDocument
GET http://{{host}}/document/ HTTP/1.1
content-type: application/json

### the csv_filename must have a coincidence with the unique_identifier of the document created in the previous step

POST http://{{host}}/transactions/import?csv_filename={{getDocument.response.body.$.documents[1].unique_identifier}} HTTP/1.1
content-type: application/json

