@host = localhost:8000

###

POST http://{{host}}/documents/bulk HTTP/1.1
content-type: application/json

{
  "base_directory": "/downloads/documents",
  "user_email": "admin@bcpextractor.com"
}

###

# @name getDocuments
GET http://{{host}}/documents/ HTTP/1.1
content-type: application/json

###

# @name createTransactions
POST http://{{host}}/transactions/bulk HTTP/1.1
content-type: application/json

{
  "account_id": "{{getDocuments.response.body.$.documents[1].account_id}}"
}

###

# @name getDocuments
GET http://{{host}}/documents/ HTTP/1.1
content-type: application/json

###

# @name importTransactions
POST http://{{host}}/transactions/import?csv_filename={{getDocuments.response.body.$.documents[1].id}} HTTP/1.1
content-type: application/json

###

# @name exportTransactions
GET http://{{host}}/transactions/export?document_id={{getDocuments.response.body.$.documents[1].id}} HTTP/1.1
content-type: application/json



### temporal

DELETE http://{{host}}/documents/{{getDocuments.response.body.$.documents[1].id}} HTTP/1.1
content-type: application/json