@host = localhost:8000
@selectedAccountId = {{readAccounts.response.body.$.accounts[4].id}}

###

# TODO: fix the code inside this endpoint. It is using the email and not the id
POST http://{{host}}/users/00000000-0000-0000-0000-000000000001/documents/ HTTP/1.1
content-type: application/json

{
  "base_directory": "/downloads/documents",
  "user_email": "admin@bcpextractor.com"
}

###

# @name readAccounts
GET http://{{host}}/accounts HTTP/1.1

###

POST http://{{host}}/accounts/{{selectedAccountId}}/transactions HTTP/1.1

###

POST http://{{host}}/accounts/{{selectedAccountId}}/histories HTTP/1.1

###

# @name importTransactions
POST http://{{host}}/transactions/import?account_id={{selectedAccountId}} HTTP/1.1
content-type: application/json

###

# @name exportTransactions
GET http://{{host}}/transactions/export?account_id={{selectedAccountId}} HTTP/1.1

### temporal

# @name readDocuments
GET http://{{host}}/documents/ HTTP/1.1
content-type: application/json

###

DELETE http://{{host}}/documents/{{readDocuments.response.body.$.documents[1].id}} HTTP/1.1
content-type: application/json


### -----------------------------------------------

POST http://{{host}}/histories