/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * BCP PDF Extractor
 * Extracts transactions from PDF documents and manages document types.
 * OpenAPI spec version: 2.0.0
 */
import type {
  DTOCreateTransactionsResponse,
  DTOExportTransactionsResponse,
  DTOGetAllTransactionsResponse,
  DTOImportTransactionsFromCsvResponse,
  DTOUpdateTransactionRequest,
  DTOUpdateTransactionResponse,
  DTOUpdateTransactionsRequest,
  DTOUpdateTransactionsResponse,
  ExportTransactionsTransactionsExportCsvGetParams,
  GetTransactionsTransactionsGetParams,
  HTTPValidationError,
  ImportTransactionsFromCsvTransactionsImportCsvPostParams
} from '../bcp.schemas';


export type getTransactionsTransactionsGetResponse200 = {
  data: DTOGetAllTransactionsResponse
  status: 200
}

export type getTransactionsTransactionsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getTransactionsTransactionsGetResponseSuccess = (getTransactionsTransactionsGetResponse200) & {
  headers: Headers;
};
export type getTransactionsTransactionsGetResponseError = (getTransactionsTransactionsGetResponse422) & {
  headers: Headers;
};

export type getTransactionsTransactionsGetResponse = (getTransactionsTransactionsGetResponseSuccess | getTransactionsTransactionsGetResponseError)

export const getGetTransactionsTransactionsGetUrl = (params?: GetTransactionsTransactionsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://new-service:8000/transactions/?${stringifiedParams}` : `http://new-service:8000/transactions/`
}

/**
 * Get all transactions with pagination
 *
 * Includes category_name and document_type_name fields.
 *
 * Args:
 *     skip: Number of records to skip (default: 0)
 *     limit: Maximum number of records to return (default: 100, max: 1000)
 *     session: Database session (injected)
 *
 * Returns:
 *     List of transactions with category_name included
 * @summary Get Transactions
 */
export const getTransactionsTransactionsGet = async (params?: GetTransactionsTransactionsGetParams, options?: RequestInit): Promise<getTransactionsTransactionsGetResponse> => {

  const res = await fetch(getGetTransactionsTransactionsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getTransactionsTransactionsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTransactionsTransactionsGetResponse
}


export type createTransactionsTransactionsDocumentIdPostResponse200 = {
  data: DTOCreateTransactionsResponse
  status: 200
}

export type createTransactionsTransactionsDocumentIdPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createTransactionsTransactionsDocumentIdPostResponseSuccess = (createTransactionsTransactionsDocumentIdPostResponse200) & {
  headers: Headers;
};
export type createTransactionsTransactionsDocumentIdPostResponseError = (createTransactionsTransactionsDocumentIdPostResponse422) & {
  headers: Headers;
};

export type createTransactionsTransactionsDocumentIdPostResponse = (createTransactionsTransactionsDocumentIdPostResponseSuccess | createTransactionsTransactionsDocumentIdPostResponseError)

export const getCreateTransactionsTransactionsDocumentIdPostUrl = (documentId: string,) => {




  return `http://new-service:8000/transactions/${documentId}`
}

/**
 * Load transactions from a document's data column into the transactions table.
 *
 * This endpoint delegates to the application layer use case.
 *
 * Args:
 *     document_id: The UUID of the document to load transactions from
 *     session: Database session (injected)
 *
 * Returns:
 *     Summary of loaded transactions
 *
 * Raises:
 *     HTTPException: 404 if document not found, 400 for validation errors
 * @summary Create Transactions
 */
export const createTransactionsTransactionsDocumentIdPost = async (documentId: string, options?: RequestInit): Promise<createTransactionsTransactionsDocumentIdPostResponse> => {

  const res = await fetch(getCreateTransactionsTransactionsDocumentIdPostUrl(documentId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createTransactionsTransactionsDocumentIdPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createTransactionsTransactionsDocumentIdPostResponse
}


export type updateTransactionTransactionsTransactionIdPutResponse200 = {
  data: DTOUpdateTransactionResponse
  status: 200
}

export type updateTransactionTransactionsTransactionIdPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateTransactionTransactionsTransactionIdPutResponseSuccess = (updateTransactionTransactionsTransactionIdPutResponse200) & {
  headers: Headers;
};
export type updateTransactionTransactionsTransactionIdPutResponseError = (updateTransactionTransactionsTransactionIdPutResponse422) & {
  headers: Headers;
};

export type updateTransactionTransactionsTransactionIdPutResponse = (updateTransactionTransactionsTransactionIdPutResponseSuccess | updateTransactionTransactionsTransactionIdPutResponseError)

export const getUpdateTransactionTransactionsTransactionIdPutUrl = (transactionId: string,) => {




  return `http://new-service:8000/transactions/${transactionId}`
}

/**
 * Update a specific transaction by ID.
 *
 * This endpoint delegates to the application layer use case.
 *
 * Args:
 *     transaction_id: The UUID of the transaction to update
 *     transaction_update: The fields to update
 *     session: Database session (injected)
 *
 * Returns:
 *     Update result with transaction information
 *
 * Raises:
 *     HTTPException: 404 if transaction not found, 400 for validation errors
 * @summary Update Transaction
 */
export const updateTransactionTransactionsTransactionIdPut = async (transactionId: string,
    dTOUpdateTransactionRequest: DTOUpdateTransactionRequest, options?: RequestInit): Promise<updateTransactionTransactionsTransactionIdPutResponse> => {

  const res = await fetch(getUpdateTransactionTransactionsTransactionIdPutUrl(transactionId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(dTOUpdateTransactionRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateTransactionTransactionsTransactionIdPutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateTransactionTransactionsTransactionIdPutResponse
}


export type updateTransactionsTransactionsBatchPutResponse200 = {
  data: DTOUpdateTransactionsResponse
  status: 200
}

export type updateTransactionsTransactionsBatchPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateTransactionsTransactionsBatchPutResponseSuccess = (updateTransactionsTransactionsBatchPutResponse200) & {
  headers: Headers;
};
export type updateTransactionsTransactionsBatchPutResponseError = (updateTransactionsTransactionsBatchPutResponse422) & {
  headers: Headers;
};

export type updateTransactionsTransactionsBatchPutResponse = (updateTransactionsTransactionsBatchPutResponseSuccess | updateTransactionsTransactionsBatchPutResponseError)

export const getUpdateTransactionsTransactionsBatchPutUrl = () => {




  return `http://new-service:8000/transactions/batch`
}

/**
 * Update multiple transactions simultaneously.
 *
 * Only 'history' and 'category_name' fields can be updated for each transaction.
 * If category_name is provided, it will be validated against existing categories.
 * This endpoint processes all updates and returns a summary of the operation.
 *
 * Args:
 *     batch_update: List of transaction updates to apply
 *     session: Database session (injected)
 *
 * Returns:
 *     Summary of batch update operation with success/failure counts
 *
 * Raises:
 *     HTTPException: 400 for validation errors
 * @summary Update Transactions
 */
export const updateTransactionsTransactionsBatchPut = async (dTOUpdateTransactionsRequest: DTOUpdateTransactionsRequest, options?: RequestInit): Promise<updateTransactionsTransactionsBatchPutResponse> => {

  const res = await fetch(getUpdateTransactionsTransactionsBatchPutUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(dTOUpdateTransactionsRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateTransactionsTransactionsBatchPutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateTransactionsTransactionsBatchPutResponse
}


export type exportTransactionsTransactionsExportCsvGetResponse200 = {
  data: DTOExportTransactionsResponse
  status: 200
}

export type exportTransactionsTransactionsExportCsvGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type exportTransactionsTransactionsExportCsvGetResponseSuccess = (exportTransactionsTransactionsExportCsvGetResponse200) & {
  headers: Headers;
};
export type exportTransactionsTransactionsExportCsvGetResponseError = (exportTransactionsTransactionsExportCsvGetResponse422) & {
  headers: Headers;
};

export type exportTransactionsTransactionsExportCsvGetResponse = (exportTransactionsTransactionsExportCsvGetResponseSuccess | exportTransactionsTransactionsExportCsvGetResponseError)

export const getExportTransactionsTransactionsExportCsvGetUrl = (params?: ExportTransactionsTransactionsExportCsvGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://new-service:8000/transactions/export/csv?${stringifiedParams}` : `http://new-service:8000/transactions/export/csv`
}

/**
 * Export transactions to CSV format and save to file
 *
 * Filters:
 *     - month: Optional filter by month in format YYYY-MM (e.g., "2025-01")
 *     - document_id: Optional filter by specific document
 *     - output_dir: Output directory for CSV file (default: ./exports)
 *
 * Returns:
 *     JSON with file path, transaction count, and status
 *
 * Examples:
 *     - GET /transactions/export/csv - Export all transactions
 *     - GET /transactions/export/csv?month=2025-01 - Export transactions from January 2025
 *     - GET /transactions/export/csv?document_id=xxx-xxx-xxx - Export transactions from specific document
 *     - GET /transactions/export/csv?month=2025-01&document_id=xxx-xxx-xxx - Combined filters
 * @summary Export Transactions
 */
export const exportTransactionsTransactionsExportCsvGet = async (params?: ExportTransactionsTransactionsExportCsvGetParams, options?: RequestInit): Promise<exportTransactionsTransactionsExportCsvGetResponse> => {

  const res = await fetch(getExportTransactionsTransactionsExportCsvGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: exportTransactionsTransactionsExportCsvGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as exportTransactionsTransactionsExportCsvGetResponse
}


export type importTransactionsFromCsvTransactionsImportCsvPostResponse200 = {
  data: DTOImportTransactionsFromCsvResponse
  status: 200
}

export type importTransactionsFromCsvTransactionsImportCsvPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type importTransactionsFromCsvTransactionsImportCsvPostResponseSuccess = (importTransactionsFromCsvTransactionsImportCsvPostResponse200) & {
  headers: Headers;
};
export type importTransactionsFromCsvTransactionsImportCsvPostResponseError = (importTransactionsFromCsvTransactionsImportCsvPostResponse422) & {
  headers: Headers;
};

export type importTransactionsFromCsvTransactionsImportCsvPostResponse = (importTransactionsFromCsvTransactionsImportCsvPostResponseSuccess | importTransactionsFromCsvTransactionsImportCsvPostResponseError)

export const getImportTransactionsFromCsvTransactionsImportCsvPostUrl = (params?: ImportTransactionsFromCsvTransactionsImportCsvPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://new-service:8000/transactions/import/csv?${stringifiedParams}` : `http://new-service:8000/transactions/import/csv`
}

/**
 * Import and update transactions from CSV file
 *
 * Reads a CSV file from the specified directory and updates transactions based on unique_identifier.
 * Updates the 'history' and 'category_name' fields for matching transactions.
 *
 * Args:
 *     csv_filename: Optional specific CSV filename. If not provided, uses the most recent CSV file.
 *     input_dir: Directory where to read the CSV file from (default: /shared_files/output)
 *
 * Returns:
 *     JSON with import summary including updated count, errors, etc.
 *
 * Examples:
 *     - POST /transactions/import/csv - Import from latest CSV file in default directory
 *     - POST /transactions/import/csv?input_dir=/custom/path - Import from custom directory
 *     - POST /transactions/import/csv?csv_filename=transactions.csv - Import from specific file
 *     - POST /transactions/import/csv?csv_filename=transactions.csv&input_dir=/custom/path - Custom file and directory
 * @summary Import Transactions From Csv
 */
export const importTransactionsFromCsvTransactionsImportCsvPost = async (params?: ImportTransactionsFromCsvTransactionsImportCsvPostParams, options?: RequestInit): Promise<importTransactionsFromCsvTransactionsImportCsvPostResponse> => {

  const res = await fetch(getImportTransactionsFromCsvTransactionsImportCsvPostUrl(params),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: importTransactionsFromCsvTransactionsImportCsvPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as importTransactionsFromCsvTransactionsImportCsvPostResponse
}


