/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * BCP PDF Extractor
 * Extracts transactions from PDF documents and manages document types.
 * OpenAPI spec version: 2.0.0
 */
import type {
  DTOCreateDocumentRequest,
  DTOCreateDocumentResponse,
  DTOGetDocumentsResponse,
  DeleteDocumentDocumentDocumentIdDelete200,
  GetDocumentsDocumentGetParams,
  HTTPValidationError
} from '../bcp.schemas';


export type getDocumentsDocumentGetResponse200 = {
  data: DTOGetDocumentsResponse
  status: 200
}

export type getDocumentsDocumentGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getDocumentsDocumentGetResponseSuccess = (getDocumentsDocumentGetResponse200) & {
  headers: Headers;
};
export type getDocumentsDocumentGetResponseError = (getDocumentsDocumentGetResponse422) & {
  headers: Headers;
};

export type getDocumentsDocumentGetResponse = (getDocumentsDocumentGetResponseSuccess | getDocumentsDocumentGetResponseError)

export const getGetDocumentsDocumentGetUrl = (params?: GetDocumentsDocumentGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/document/?${stringifiedParams}` : `http://localhost:8000/document/`
}

/**
 * Get all documents with pagination
 *
 * Returns all documents with their properties including:
 * - id, unique_identifier
 * - processed status, user_id, document_type_id
 * - transactions count
 * @summary Get Documents
 */
export const getDocumentsDocumentGet = async (params?: GetDocumentsDocumentGetParams, options?: RequestInit): Promise<getDocumentsDocumentGetResponse> => {

  const res = await fetch(getGetDocumentsDocumentGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getDocumentsDocumentGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDocumentsDocumentGetResponse
}


export type createDocumentDocumentPostResponse200 = {
  data: DTOCreateDocumentResponse
  status: 200
}

export type createDocumentDocumentPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createDocumentDocumentPostResponseSuccess = (createDocumentDocumentPostResponse200) & {
  headers: Headers;
};
export type createDocumentDocumentPostResponseError = (createDocumentDocumentPostResponse422) & {
  headers: Headers;
};

export type createDocumentDocumentPostResponse = (createDocumentDocumentPostResponseSuccess | createDocumentDocumentPostResponseError)

export const getCreateDocumentDocumentPostUrl = () => {




  return `http://localhost:8000/document/`
}

/**
 * Process a PDF file and save extracted data to the Documents table
 *
 * - **pdf_filepath**: PDF file path (e.g., "files/document.pdf")
 * - **document_type**: Account type ("debit" or "credit")
 * - **user_email**: User email (optional, defaults to admin@bcpextractor.com)
 * - Extracted data is saved as JSON in the 'data' column of the Documents table
 * @summary Create Document
 */
export const createDocumentDocumentPost = async (dTOCreateDocumentRequest: DTOCreateDocumentRequest, options?: RequestInit): Promise<createDocumentDocumentPostResponse> => {

  const res = await fetch(getCreateDocumentDocumentPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(dTOCreateDocumentRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createDocumentDocumentPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createDocumentDocumentPostResponse
}


export type deleteDocumentDocumentDocumentIdDeleteResponse200 = {
  data: DeleteDocumentDocumentDocumentIdDelete200
  status: 200
}

export type deleteDocumentDocumentDocumentIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteDocumentDocumentDocumentIdDeleteResponseSuccess = (deleteDocumentDocumentDocumentIdDeleteResponse200) & {
  headers: Headers;
};
export type deleteDocumentDocumentDocumentIdDeleteResponseError = (deleteDocumentDocumentDocumentIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteDocumentDocumentDocumentIdDeleteResponse = (deleteDocumentDocumentDocumentIdDeleteResponseSuccess | deleteDocumentDocumentDocumentIdDeleteResponseError)

export const getDeleteDocumentDocumentDocumentIdDeleteUrl = (documentId: string,) => {




  return `http://localhost:8000/document/${documentId}`
}

/**
 * @summary Delete Document
 */
export const deleteDocumentDocumentDocumentIdDelete = async (documentId: string, options?: RequestInit): Promise<deleteDocumentDocumentDocumentIdDeleteResponse> => {

  const res = await fetch(getDeleteDocumentDocumentDocumentIdDeleteUrl(documentId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteDocumentDocumentDocumentIdDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteDocumentDocumentDocumentIdDeleteResponse
}


