/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * BCP PDF Extractor
 * Extracts transactions from PDF documents and manages document types.
 * OpenAPI spec version: 2.0.0
 */
import type {
  DTOGetAllDocumentTypesResponse
} from '../bcp.schemas';


export type getAllDocumentTypesDocumentTypesGetResponse200 = {
  data: DTOGetAllDocumentTypesResponse
  status: 200
}

export type getAllDocumentTypesDocumentTypesGetResponseSuccess = (getAllDocumentTypesDocumentTypesGetResponse200) & {
  headers: Headers;
};
;

export type getAllDocumentTypesDocumentTypesGetResponse = (getAllDocumentTypesDocumentTypesGetResponseSuccess)

export const getGetAllDocumentTypesDocumentTypesGetUrl = () => {




  return `http://new-service:8000/document-types/`
}

/**
 * Get all document types
 *
 * Returns:
 *     List of all document types with their details
 * @summary Get All Document Types
 */
export const getAllDocumentTypesDocumentTypesGet = async ( options?: RequestInit): Promise<getAllDocumentTypesDocumentTypesGetResponse> => {

  const res = await fetch(getGetAllDocumentTypesDocumentTypesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAllDocumentTypesDocumentTypesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllDocumentTypesDocumentTypesGetResponse
}


