/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * BCP PDF Extractor
 * Extracts transactions from PDF documents and manages document types.
 * OpenAPI spec version: 2.0.0
 */

export type rootApiGetResponse200 = {
  data: unknown
  status: 200
}

export type rootApiGetResponseSuccess = (rootApiGetResponse200) & {
  headers: Headers;
};
;

export type rootApiGetResponse = (rootApiGetResponseSuccess)

export const getRootApiGetUrl = () => {




  return `http://new-service:8000/api`
}

/**
 * Root endpoint for health check and service information.
 * @summary Root
 */
export const rootApiGet = async ( options?: RequestInit): Promise<rootApiGetResponse> => {

  const res = await fetch(getRootApiGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rootApiGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rootApiGetResponse
}


